### ISSUE TITLE
opensource community standards 

### ISSUE THREAD

**Issue by benceHornyak** [ExamProCo/fast-author#1]
Hi

Saw your post on dev.to, I thought I give you a heads up: you might want to fill these: https://github.com/ExamProCo/fast-author/community and also check https://opensource.guide/ .

I really like your project. :+1:

**Comment by omenking** [comment]
Checking the out now. Thank you!

**Comment by omenking** [comment]
Done!
![Screen Shot 2020-02-15 at 11 02 46 PM](https://user-images.githubusercontent.com/7776/74598868-4cd2b980-5047-11ea-96c6-565564614725.png)
